// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const durations = {
 "short": "0.15s",
 "medium": "0.25s",
 "long": "0.6s",
 "veryLong": "1s"
} as const;

export default durations;